#Whenever our program generates anything, it will be stored in artifacts
artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    service: s3
    region: ap-southeast-2
    bucket_name: amaterasu
    aws_file: Transaction.csv
    download_path: artifacts/data_ingestion/data.csv


data_prepocess:
    root_dir: artifacts/model_data
    drop_feature: ["Timestamp","Account","account"]
    categorical_feature: ['receiving_currency', 'Payment_Currency', 'Payment Format',"is_laundering"]
    continuous_feature: ['from_bank', 'to_bank', 'amount_received', 'amount_paid']
    save_processed_data: artifacts/model_data/processed_data.csv

prepare_base_model:
    root_dir: artifacts/prepare_base_model
    base_model_path: artifacts/prepare_base_model/base_model.plk


eval_model:
    root_dir: artifacts/eval
    path_of_model: artifacts/prepare_base_model/base_model.plk
    training_data: artifacts/model_data/processed_data.csv
    mlflow_url: https://dagshub.com/adirajjohn2000/AML_Classification.mlflow

