#Whenever our program generates anything, it will be stored in artifacts
artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    service: s3
    region: ap-southeast-2
    bucket_name: amaterasu
    aws_file: Transaction.csv
    download_path: artifacts/data_ingestion/data.csv